// args
var destServ = args[0];
var hackTargetServ = args[1];

// files to copy over
var scripts = [
    "/master/functions/getRootAccess-ns1.script",
    "/master/hacking/advanced/run-ns1.script",
    "/master/hacking/helpers/grow_target-ns1.script",
    "/master/hacking/helpers/hack_target-ns1.script",
    "/master/hacking/helpers/weaken_target-ns1.script"
    ];

var primaryScript = "/master/hacking/advanced/run-ns1.script";

var sourceServer = "home";

scp(scripts, sourceServer, destServ);
exec(primaryScript, destServ, 1, hackTargetServ);