// ===== IMPORTS ================================
import {getRootAccess} from "/master/functions/getRootAccess-ns1.script";
var ePortIndex = enumLib.getEnumPortIndexVersion(1);
var portEmpty = "NULL PORT DATA";

// ===== ARGS ===================================
var sArgs = {
	initialHackTarget : args[0],	// Initial to hack
};

// ===== VARS ===================================
var sVars = {
	moneyThreshModPcnt : 0.75,
	securityThreshModAdd : 5,
};

var tests = {
	enabled : false, // Master override for all tests
	testExampleEnabled : false,
};

// ===== MAIN ===================================
main();

function main() {
	var sArgs = getScriptArgs();
	
	// - Tests ----------------------------------
	if (tests.enabled)
		executeTests();
	
	// - Early out ------------------------------
	if (tests.disableMain) {
		tprint("WARNING: SCRIPT IS IN TEST ONLY MODE");
		exit();
	}

	// - Real Script Logic ----------------------

	// Setting up some thresholds
	var moneyThresh = getServerMaxMoney(sArgs.initialHackTarget) * sVars.moneyThreshModPcnt;
	var securityThresh = getServerMinSecurityLevel(sArgs.initialHackTarget) + sVars.securityThreshModAdd;

	// Get root access if I don't have it
	if (hasRootAccess(sArgs.initialHackTarget) === false) {
		getRootAccess(sArgs.initialHackTarget);
	}

	while(true) {
		if (getServerSecurityLevel(sArgs.initialHackTarget) > securityThresh) {
			// If the server's security level is above our threshold, weaken it
			weaken(sArgs.initialHackTarget);
		} else if (getServerMoneyAvailable(sArgs.initialHackTarget) < moneyThresh) {
			// If the server's money is less than our threshold, grow it
			grow(sArgs.initialHackTarget);
		} else {
			// Otherwise, hack it
			hack(sArgs.initialHackTarget);
		}
	}
}

// ===== FUNCTIONS ==============================


// ===== TESTS ==================================
function executeTests(ns) {
	if (tests.testExampleEnabled)
		testExample(ns);
}

function testExample(ns) {
	ns.print("==== TEST: testExample ====");

}